name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  CI_REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  IMAGE_TAG: ${{ secrets.IMAGE_TAG }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.CI_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to Server
        run: |
          ssh ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_STATIC_IP }} "
          docker rm -f ${{ secrets.CONTAINER_NAME }} || true &&
          docker image rm -f ${{ env.CI_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} || true &&
          docker run --name ${{ secrets.CONTAINER_NAME }} -p ${{ secrets.PORT }}:8000 -d ${{ env.CI_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"